###
# @name Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###
# @name Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###
# @name Get Users (Unauthorized)
GET http://localhost:3000/api/users

###
# @name Get Users (Authorized)
GET http://localhost:3000/api/users
Authorization: Bearer {{Login User.response.body.token}}


###
# @name Post Liked Movies (Authorized)
POST http://localhost:3000/api/:userId/liked
Authorization: Bearer {{Login User.response.body.token}}
Content-Type: application/json

{
  "userId": 1,
  "movieId": "812381"
}